# Generated by Django 5.0.8 on 2024-08-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_location_journalentry_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
